using System;

namespace COVID_19_LFT_Logging_System
{
    public enum TestType
    {
        LFD,
        PCR
    }
    class Test
    {
        private int id; // automatically generated by database
        private TestType type; // LFD or PCR
        private string barcode;
        private DateTime timestamp;
        private bool contactTesting;
        private bool symptoms;
        private DateTime symptomsDate; // nullable; only relevant if symptoms is True
        private int patientId; // nullable;

        public Test(TestType type, string barcode, DateTime timestamp, bool contactTesting, bool symptoms, int patientId)
        {
            this.type = type;
            this.barcode = barcode;
            this.timestamp = timestamp;
            this.contactTesting = contactTesting;
            this.symptoms = symptoms;
            this.patientId = patientId;
        }

        // "Detached" test - no patient attached to this test
        public Test(TestType type, string barcode, DateTime timestamp, bool contactTesting, bool symptoms)
        {
            this.type = type;
            this.barcode = barcode;
            this.timestamp = timestamp;
            this.contactTesting = contactTesting;
            this.symptoms = symptoms;
        }

        public int Id { get => id; set => id = value; }
        public TestType Type { get => type; set => type = value; }
        public string Barcode { get => barcode; set => barcode = value; }
        public DateTime Timestamp { get => timestamp; set => timestamp = value; }
        public bool DailyContactTesting { get => contactTesting; set => contactTesting = value; }
        public bool HasSymptoms { get => symptoms; set => symptoms = value; }
        public DateTime SymptomsStartDate { get => symptomsDate; set => symptomsDate = value; }
        public int PatientId { get => patientId; set => patientId = value; }
    }
}
